server:
  port: 8083
#
spring:
  application:
    name: ApiGateway
  cloud:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
      - id: EmovieApp
        uri:  lb://EmovieApp
        predicates:
        - Path=/api/v1/moviesapp/**
      - id: User
        uri:  lb://User
        predicates:
        - Path=/api/v1/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
            allowedHeaders:
            - "*"
            allowCredentials: false
              
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true